name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: "Build and deploy to Netlify"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Source
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install
        npm run build
        npm run export
    - name: Publish Site
      uses: nwtgck/actions-netlify@v1.1
      with:
        publish-dir: './out'
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    