name: CI-CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: "Build and deploy to Netlify"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Source
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        yarn install --frozen-lockfile
        yarn build
        yarn export
    - name: Publish Site
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=${{ github.workspace }}/out
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    